- name: mysql
  hosts: mysql
  become: yes 
  tasks: 
    - name: Disable mysql current version
      ansible.builtin.command: dnf module disable mysql -y
        
    - name: Copy mysql repo
      ansible.builtin.copy:
      src: mysql.repo
      dest: /etc/yum.repos.d/mysql.repo

    - name: Install mysql
      ansible.builtin.dnf:
        name: mysql-community-server # if it wont work use package module
        state: present

    - name: Start and Enable mysql
      ansible.builtin.service:
        name: mysqld
        state: restarted
        enabled: yes

    - name: setup root password
      ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1