- name: installing redis component
  hosts: redis
  become: yes
  tasks:
    - name: installing remi repo 8
      ansible.builtin.dnf:
        name:  https://rpms.remirepo.net/enterprise/remi-release-8.rpm
        state: present
        disable_gpg_check: true

    - name: enable redis 6.2 package
      ansible.builtin.command: dnf module enable redis:remi-6.2 -y

    - name: install redis
      ansible.builtin.dnf:
        name: redis
        state: present

    - name: allow remote connection
      ansible.builtin.replace:
        path: /etc/redis.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'

    - name: start and enable redis
      ansible.builtin.systemd:
        name: redis
        state: restarted
        enabled: yes